### ISSUE TITLE
add robot mesh in scitos_description/meshes

### ISSUE THREAD

**Issue by kunzel** [strands-project/scitos_common#2]
@hawesie, Do you still have the SCITOS robot mesh as collada file? Then we could use this instead of the cylinder to visualize the robot in RVIZ.

**Comment by hawesie** [comment]
You can just use the export menu in Blender to create it. Mine had lots of additional lines that didn't look right, so it's probably best to do a fresh export.

**Comment by kunzel** [comment]
OK, I'll make a fresh export and add it to the repository.

**Comment by kunzel** [comment]
Added in #5
