### ISSUE TITLE
New camera in urdf model

### ISSUE THREAD

**Issue by nilsbore** [strands-project/scitos_common#25]
I've added new camera, chest_xtion(don't know which type we'll be using yet) in the urdf model. Since I've made a small program for finding the ground plane and use that to find the height and the angle, I've attached it to the base_link directly. Optimally, you would just run the script and it would update your urdf model directly, but this should only be done on request since it only works when it sees a good portion of the floor. Is there any way to store these parameters into e.g. the mongodb database and then read them from there to use in the urdf model? Any thoughts otherwise, @kunzel , others?

**Comment by Jailander** [comment]
Hi, for the parameter configuration you can use the rosparam server and the mongodb interface for saving and loading these parameters (strands_utils/strands_datacentre/config_manager.py).

**Comment by nilsbore** [comment]
So I've done as you've suggested and stored the parameters /chest_xtion_height and /chest_xtion_angle in the strands_datacentre. I'm now looking into how to feed that into the tf tree. It only seems to be able to init a joint_state_publisher with params for some transforms since ros hydro. So I'll probably integrate it with the node that publishes the PTU angles. Seems a bit unnecessary to have a separate node for that.

**Comment by nilsbore** [comment]
Closing this since I went with the above solution and it seems to work.
