### ISSUE TITLE
[calibrate_chest] dependencies for data_centre in calibrate_chest (and probably others)

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_common#28]
with the refactoring of the data_centre there are misdefined dependencies it seems. This is probably one example of quite a few... Here's the failed jenkins build: http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/166/ 

relevant lines:

```
In file included from <http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/src/scitos_common/calibrate_chest/src/calibrate_chest.cpp>:8:0:
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:55:9: error: ‘SetParamResponse’ does not name a type
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:57:1: error: ‘Response’ does not name a type
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:60:9: error: ‘Response’ does not name a type
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:126:16: error: ‘SetParamResponse’ is not a member of ‘strands_datacentre’
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:126:16: error: ‘SetParamResponse’ is not a member of ‘strands_datacentre’
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:126:54: error: template argument 1 is invalid
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:141:18: error: ‘SetParamResponse’ is not a member of ‘strands_datacentre’
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:141:18: error: ‘SetParamResponse’ is not a member of ‘strands_datacentre’
<http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/ws/catkin_ws/devel/include/strands_datacentre/SetParam.h>:141:56: error: template argument 1 is invalid
```

**Comment by nilsbore** [comment]
I'll have a look at this. scitos_common should be able to depend on the ros_datacentre, right? So it's just a matter of fixing the dependencies in the code?

**Comment by hawesie** [comment]
As far as I know the dependencies should not need to change as the ros_datacentre repository (not package) contains the packages which were previously available. The package names have not changed, so I didn't think the dependencies should need to change. I haven't had time to look closely though.

**Comment by nilsbore** [comment]
Also, does strands_datacentre have to be a run dependency in the package.xml or only a build dependency? I seem to only have added it as a build dependency.

**Comment by marc-hanheide** [comment]
Indeed, this is again a problem of parallel build. In the [compile log](http://lcas.lincoln.ac.uk/jenkins/job/catkin_make_strands_desktop_full/169/console) it is clear that `calibrate_chest` is being build while also the `strands_datacentre` is being build at the same time. That causes the problem. I believe that in the [CMakeLists.txt](https://github.com/strands-project/scitos_common/blob/master/calibrate_chest/CMakeLists.txt) there is some `add_dependencies(calibrate_chest strands_datacentre)` (and probably others more???) missing. I don't have it checked out here at the moment, so I cannot try myself.

**Comment by hawesie** [comment]
Should that `add_dependencies` be explicitly needed? I thought the package.xml or some other ROS magic handled it.

**Comment by marc-hanheide** [comment]
Hmm, I'm no expert, but it was needed in _many_ other places and I couldn't find any documentation right now that says that it is enough to put it in `package.xml`. All examples have the dependencies listed there as well. Maybe because in the `CMakeLists.txt` you define them per "make target" (e.g. a binary or lib), and not globally. I think the dependencies in `package.xml` are just used to check the the package is found, compile dependencies are still all modelled in `CMakeLists.txt`.

**Comment by nilsbore** [comment]
If you look at the examples it indeed looks like the add dependencies should be added. I'm away at a conference until the evening today, I will add that and potentially other stuff then. However I have built this in parallell myself and it worked then so I can only see that it works for me.

**Comment by cdondrup** [comment]
When ever you use custom messages/services you have to depend on the target `<package_name>_gencpp` or `<package_name>_generate_messages_cpp` which can be used equivalently. The letter is a newer version of gencpp with a bit more sensible name. If you do, catkin will make sure that the *.h files you include are built before your code is built. If you don't include it, it will just built out of pure coincidence. The package.xml does not influence this behaviour in any way and is therefore just useful for the initial cmake configure step to check if the necessary packages exist.

**Comment by hawesie** [comment]
When you say "depend" do you mean `add_dependencies`?

**Comment by cdondrup** [comment]
Yes, should have mentioned that, sorry.
So it is always: `add_dependencies(cmake_build_target another_package_generate_messages_cpp)` or `add_dependencies(cmake_build_target another_package_gencpp)`

So in this case the correct way of doing it would be to add:

```
...
## Declare a cpp executable
add_executable(calibrate_chest src/calibrate_chest.cpp)
add_executable(chest_calibration_publisher src/chest_calibration_publisher.cpp)

add_dependencies(calibrate_chest strands_datacentre_generate_messages_cpp)
...
```

**Comment by cdondrup** [comment]
Of course the other package also has to be listed in the `find_package(catkin REQUIRED COMPONENTS ...)` statement which is already the case for chest calibration.

Btw.: all this is obviously just important for C++ and can be completely ignored for python.

**Comment by nilsbore** [comment]
@cdondrup Thank you very much for the pointers! I had not seen this before.
